import type { Meeting } from "../api/meetingApi";

/* -------------------------------- */
/* HELPERS */
/* -------------------------------- */

const formatDate = (
  dateString?: string
) => {
  if (!dateString) {
    return "Unknown date";
  }

  const date = new Date(dateString);

  if (Number.isNaN(date.getTime())) {
    return "Unknown date";
  }

  return date.toLocaleString();
};

const getStatus = (
  status?: Meeting["analysisStatus"]
) => {
  switch (status) {
    case "approved":
      return "Approved";

    case "rejected":
      return "Rejected";

    case "pending":
    default:
      return "Pending Verification";
  }
};

const getActionItemStatus = (
  status: string
) => {
  switch (status) {
    case "approved":
      return "Approved";

    case "rejected":
      return "Rejected";

    default:
      return "Pending";
  }
};

const createSafeFileName = (
  title: string
) => {
  return (
    title
      .trim()
      .replace(/[^a-z0-9]+/gi, "-")
      .replace(/^-+|-+$/g, "")
      .toLowerCase() ||
    "meeting"
  );
};

const downloadBlob = (
  blob: Blob,
  fileName: string
) => {
  const url =
    URL.createObjectURL(blob);

  const link =
    document.createElement("a");

  link.href = url;
  link.download = fileName;

  document.body.appendChild(link);

  link.click();

  document.body.removeChild(link);

  URL.revokeObjectURL(url);
};

/* -------------------------------- */
/* TEXT REPORT */
/* -------------------------------- */

export const generateMeetingReport = (
  meeting: Meeting
): string => {
  const decisions =
    meeting.decisions &&
    meeting.decisions.length > 0
      ? meeting.decisions
          .map(
            (decision, index) =>
              `${index + 1}. ${decision}`
          )
          .join("\n")
      : "No decisions identified.";

  const actionItems =
    meeting.actionItems &&
    meeting.actionItems.length > 0
      ? meeting.actionItems
          .map((item, index) => {
            const details = [
              `Status: ${getActionItemStatus(
                item.status
              )}`,

              item.assignee
                ? `Assignee: ${item.assignee}`
                : "",

              item.dueDate
                ? `Due Date: ${formatDate(
                    item.dueDate
                  )}`
                : "",

              item.priority
                ? `Priority: ${item.priority}`
                : "",
            ].filter(Boolean);

            return [
              `${index + 1}. ${item.text}`,

              ...details.map(
                (detail) =>
                  `   ${detail}`
              ),
            ].join("\n");
          })
          .join("\n\n")
      : "No action items identified.";

  const unresolvedQuestions =
    meeting.unresolvedQuestions &&
    meeting.unresolvedQuestions.length > 0
      ? meeting.unresolvedQuestions
          .map(
            (question, index) =>
              `${index + 1}. ${question}`
          )
          .join("\n")
      : "No unresolved questions identified.";

  const report = `
============================================================
                         TASKIE
                  MEETING INTELLIGENCE
============================================================

MEETING
------------------------------------------------------------

Title:
${meeting.title}

Date:
${formatDate(meeting.createdAt)}

Analysis Status:
${getStatus(meeting.analysisStatus)}


SUMMARY
------------------------------------------------------------

${meeting.summary || "No summary available."}


AI NOTES
------------------------------------------------------------

${meeting.aiNotes || "No AI notes available."}


PERSONAL NOTES
------------------------------------------------------------

${meeting.personalNotes || "No personal notes available."}


DECISIONS
------------------------------------------------------------

${decisions}


ACTION ITEMS
------------------------------------------------------------

${actionItems}


UNRESOLVED QUESTIONS
------------------------------------------------------------

${unresolvedQuestions}


TRANSCRIPT
------------------------------------------------------------

${meeting.transcript || "No transcript available."}


============================================================
                    Generated by Taskie
              From Conversation → to Verified Execution
============================================================
`.trim();

  return report;
};

/* -------------------------------- */
/* TXT DOWNLOAD */
/* -------------------------------- */

export const downloadMeetingReport = (
  meeting: Meeting
) => {
  const report =
    generateMeetingReport(meeting);

  const blob = new Blob(
    [report],
    {
      type: "text/plain;charset=utf-8",
    }
  );

  const safeTitle =
    createSafeFileName(
      meeting.title
    );

  downloadBlob(
    blob,
    `taskie-${safeTitle}-report.txt`
  );
};

/* -------------------------------- */
/* JSON EXPORT */
/* -------------------------------- */

export const generateMeetingJson = (
  meeting: Meeting
) => {
  return {
    application: "Taskie",

    tagline:
      "From Conversation → to Verified Execution",

    meeting: {
      id: meeting._id,

      title: meeting.title,

      createdAt:
        meeting.createdAt || null,

      updatedAt:
        meeting.updatedAt || null,

      analysisStatus:
        meeting.analysisStatus ||
        "pending",

      summary:
        meeting.summary || "",

      aiNotes:
        meeting.aiNotes || "",

      personalNotes:
        meeting.personalNotes || "",

      decisions:
        meeting.decisions || [],

      actionItems:
        (meeting.actionItems || []).map(
          (item, index) => ({
            index,

            actionItemId:
              item.actionItemId ||
              null,

            text: item.text,

            assignee:
              item.assignee || "",

            dueDate:
              item.dueDate || null,

            priority:
              item.priority ||
              "medium",

            status: item.status,
          })
        ),

      unresolvedQuestions:
        meeting.unresolvedQuestions ||
        [],

      transcript:
        meeting.transcript || "",
    },
  };
};

export const downloadMeetingJson = (
  meeting: Meeting
) => {
  const data =
    generateMeetingJson(meeting);

  const json = JSON.stringify(
    data,
    null,
    2
  );

  const blob = new Blob(
    [json],
    {
      type: "application/json;charset=utf-8",
    }
  );

  const safeTitle =
    createSafeFileName(
      meeting.title
    );

  downloadBlob(
    blob,
    `taskie-${safeTitle}.json`
  );
};

/* -------------------------------- */
/* PDF EXPORT */
/* -------------------------------- */

const escapePdfText = (
  text: string
) => {
  return text
    .replace(/\\/g, "\\\\")
    .replace(/\(/g, "\\(")
    .replace(/\)/g, "\\)")
    .replace(/[^\x20-\x7E]/g, " ");
};

const wrapText = (
  text: string,
  maxLength = 88
) => {
  const words =
    text.split(/\s+/);

  const lines: string[] = [];

  let current = "";

  for (const word of words) {
    if (!word) {
      continue;
    }

    if (
      `${current} ${word}`.trim()
        .length > maxLength
    ) {
      if (current) {
        lines.push(current);
      }

      current = word;
    } else {
      current =
        `${current} ${word}`.trim();
    }
  }

  if (current) {
    lines.push(current);
  }

  return lines;
};

const createPdfDocument = (
  meeting: Meeting
) => {
  const content: string[] = [];

  const addHeading = (
    heading: string
  ) => {
    content.push("");
    content.push(heading);
    content.push("");
  };

  const addText = (
    text: string
  ) => {
    const lines =
      text.split("\n");

    for (const line of lines) {
      if (!line.trim()) {
        content.push("");
        continue;
      }

      content.push(
        ...wrapText(line)
      );
    }
  };

  content.push(
    "TASKIE - MEETING INTELLIGENCE"
  );

  content.push(
    "From Conversation -> to Verified Execution"
  );

  addHeading("MEETING");

  addText(
    `Title: ${meeting.title}`
  );

  addText(
    `Date: ${formatDate(
      meeting.createdAt
    )}`
  );

  addText(
    `Analysis Status: ${getStatus(
      meeting.analysisStatus
    )}`
  );

  addHeading("SUMMARY");

  addText(
    meeting.summary ||
      "No summary available."
  );

  addHeading("AI NOTES");

  addText(
    meeting.aiNotes ||
      "No AI notes available."
  );

  addHeading(
    "PERSONAL NOTES"
  );

  addText(
    meeting.personalNotes ||
      "No personal notes available."
  );

  addHeading("DECISIONS");

  if (
    meeting.decisions &&
    meeting.decisions.length > 0
  ) {
    meeting.decisions.forEach(
      (decision, index) => {
        addText(
          `${index + 1}. ${decision}`
        );
      }
    );
  } else {
    addText(
      "No decisions identified."
    );
  }

  addHeading(
    "ACTION ITEMS"
  );

  if (
    meeting.actionItems &&
    meeting.actionItems.length > 0
  ) {
    meeting.actionItems.forEach(
      (item, index) => {
        addText(
          `${index + 1}. ${item.text}`
        );

        addText(
          `Status: ${getActionItemStatus(
            item.status
          )}`
        );

        if (item.assignee) {
          addText(
            `Assignee: ${item.assignee}`
          );
        }

        if (item.dueDate) {
          addText(
            `Due Date: ${formatDate(
              item.dueDate
            )}`
          );
        }

        if (item.priority) {
          addText(
            `Priority: ${item.priority}`
          );
        }

        content.push("");
      }
    );
  } else {
    addText(
      "No action items identified."
    );
  }

  addHeading(
    "UNRESOLVED QUESTIONS"
  );

  if (
    meeting.unresolvedQuestions &&
    meeting.unresolvedQuestions
      .length > 0
  ) {
    meeting.unresolvedQuestions.forEach(
      (question, index) => {
        addText(
          `${index + 1}. ${question}`
        );
      }
    );
  } else {
    addText(
      "No unresolved questions identified."
    );
  }

  addHeading("TRANSCRIPT");

  addText(
    meeting.transcript ||
      "No transcript available."
  );

  return content;
};

export const downloadMeetingPdf = (
  meeting: Meeting
) => {
  const lines =
    createPdfDocument(meeting);

  const pageHeight = 720;
  const top = 690;
  const lineHeight = 14;

  const linesPerPage = Math.floor(
    (top - 40) /
      lineHeight
  );

  const pages: string[][] = [];

  for (
    let i = 0;
    i < lines.length;
    i += linesPerPage
  ) {
    pages.push(
      lines.slice(
        i,
        i + linesPerPage
      )
    );
  }

  if (pages.length === 0) {
    pages.push([]);
  }

  const objects: string[] = [];

  const catalogObject = 1;
  const pagesObject = 2;
  const fontObject = 3;

  objects[fontObject - 1] =
    `<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>`;

  const pageObjectNumbers: number[] = [];

  pages.forEach((pageLines) => {
    const pageObjectNumber =
      objects.length + 1;

    const contentObjectNumber =
      pageObjectNumber + 1;

    pageObjectNumbers.push(
      pageObjectNumber
    );

    const commands: string[] = [
      "BT",
      "/F1 10 Tf",
      `50 ${top} Td`,
    ];

    for (
      let i = 0;
      i < pageLines.length;
      i++
    ) {
      const line =
        escapePdfText(
          pageLines[i]
        );

      if (i > 0) {
        commands.push(
          `0 -${lineHeight} Td`
        );
      }

      commands.push(
        `(${line}) Tj`
      );
    }

    commands.push("ET");

    const stream =
      commands.join("\n");

    objects[
      contentObjectNumber - 1
    ] =
      `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`;

    objects[
      pageObjectNumber - 1
    ] =
      `<< /Type /Page /Parent ${pagesObject} 0 R /MediaBox [0 0 612 ${pageHeight}] /Resources << /Font << /F1 ${fontObject} 0 R >> >> /Contents ${contentObjectNumber} 0 R >>`;
  });

  objects[catalogObject - 1] =
    `<< /Type /Catalog /Pages ${pagesObject} 0 R >>`;

  const kids =
    pageObjectNumbers
      .map(
        (number) =>
          `${number} 0 R`
      )
      .join(" ");

  objects[pagesObject - 1] =
    `<< /Type /Pages /Kids [${kids}] /Count ${pageObjectNumbers.length} >>`;

  let pdf =
    "%PDF-1.4\n";

  const offsets: number[] = [0];

  objects.forEach(
    (object, index) => {
      offsets.push(
        pdf.length
      );

      pdf +=
        `${index + 1} 0 obj\n`;

      pdf +=
        `${object}\n`;

      pdf +=
        "endobj\n";
    }
  );

  const xrefOffset =
    pdf.length;

  pdf +=
    `xref\n0 ${objects.length + 1}\n`;

  pdf +=
    "0000000000 65535 f \n";

  for (
    let i = 1;
    i < offsets.length;
    i++
  ) {
    pdf +=
      `${String(
        offsets[i]
      ).padStart(
        10,
        "0"
      )} 00000 n \n`;
  }

  pdf +=
    `trailer\n<< /Size ${
      objects.length + 1
    } /Root ${catalogObject} 0 R >>\n`;

  pdf +=
    `startxref\n${xrefOffset}\n%%EOF`;

  const bytes =
    new TextEncoder().encode(
      pdf
    );

  const blob = new Blob(
    [bytes],
    {
      type: "application/pdf",
    }
  );

  const safeTitle =
    createSafeFileName(
      meeting.title
    );

  downloadBlob(
    blob,
    `taskie-${safeTitle}.pdf`
  );
};